name: lumi-dev
services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: lumi
      POSTGRES_PASSWORD: iykykoknoyes
      POSTGRES_DB: lumi
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "4567:6379"
    volumes:
      - redis_data:/data
  
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":5001"
    ports:
      - "5000:9000"
      - "5001:5001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: sawssawssaws
    volumes:
      - minio_data:/data

  ml:
    build:
      context: ./ml
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - huggingface_cache:/root/.cache/huggingface

volumes:
  postgres_data:
  redis_data:
  minio_data:
  huggingface_cache: